= Simple gRPC Wallet

== References :

https://github.com/LogNet/grpc-spring-boot-starter

https://grpc.io/

https://vladmihalcea.com/a-beginners-guide-to-database-locking-and-the-lost-update-phenomena/

== Versions :
pasha-grpc-wallet-cache:

manual cache saving latest balances database fetches.

pasha-grpc-wallet-practical :

Used hibernate annotations preventing 'LOST UPDATES'.


== Features

Protocol Buffer version : *proto3*

Spring boot version : *2.x.x*.

== Setup

Database initialization :

set__ hibernate.hbm2ddl.auto=update__

For elder MySql versions uncomment :

_#database.driverClassName=com.mysql.jdbc.Driver_

== Run

For client simulation set variables and run test unit in WalletClientTest class :

[source,java]

    walletClient.setNumberOfCuncurrentUsers(15); //Users number
    walletClient.setConcurrentThreadsPerUser(5);  //Threads per user
    walletClient.setRoundsPerThread(4);  //Rounds per thread
    @Test
    public void testClient() throws InterruptedException {
        walletClient.run();
    }


For server run test unit in ServerApiTest class :

[source,java]
@Test
    public void serverTest() {...}


== Performance 

*Run both projects with same circumstances and same parameters :


pasha-grpc-wallet-cache :
after running application run this query on database : 
[source,sql]
select count(*)  , TIMESTAMPDIFF(SECOND ,min(TRANSACTION_TIME ),max(TRANSACTION_TIME)) as seconds from fund;


pasha-grpc-wallet-practical :
after running application run this query on database : 
[source,sql]
select count(*) ,  TIMESTAMPDIFF(SECOND,min(date),max(date)) as seconds from t_transaction;


